---
title: "Intro to sf package for Spatial Data and Making Maps"
author: "Britne Clifton"
date: "2023-08-30"
output: html_document
---

```{r}
library(readr)
library(sf)
library(ggplot2)
library(leaflet)
library(scales)
library(ggmap)
library(dplyr)
```


```{r}
# read in shapefile using read_sf()
ak_regions <- read_sf("data/ak_regions_simp.shp")
```


```{r}
# quick plot
plot(ak_regions)
```

```{r}
class(ak_regions)
```


```{r}
head(ak_regions)
```


```{r}
glimpse(ak_regions)
```

```{r}
st_crs(ak_regions)
```

```{r}
ak_regions_3338 <- ak_regions %>%
    st_transform(crs = 3338)

st_crs(ak_regions_3338)
```


```{r}
plot(ak_regions_3338)
```

```{r}
# returns the names of all the columns in dataset
colnames(ak_regions_3338)
```

```{r}
ak_regions_3338 %>%
    select(region)

unique(ak_regions_3338$region)

ak_regions_3338 %>%
    filter(region == "Southeast")
```

```{r}
# read in population data
pop <- read_csv("data/alaska_population.csv")

pop_4326 <- st_as_sf(pop,
                     coords = c('lng', 'lat'),
                     crs = 4326,
                     remove = F)

head(pop_4326)
```

```{r}
pop_3338 <- st_transform(pop_4326, crs = 3338)

pop_joined <- st_join(pop_3338, ak_regions_3338, join = st_within)

head(pop_joined)
```

```{r}
pop_region <- pop_joined %>%
    as.data.frame() %>% # gets rid of geometry col
    group_by(region) %>%
    summarise(total_pop = sum(population))

head(pop_region)
```

```{r}
pop_region_3338 <- left_join(ak_regions_3338, pop_region, by = "region")

# plot to check
plot(pop_region_3338["total_pop"])
```

```{r}
pop_mgmt_338 <- pop_region_3338 %>%
    group_by(mgmt_area) %>%
    summarize(total_pop = sum(total_pop))

plot(pop_mgmt_338["total_pop"])
```

```{r}
pop_mgmt_3338 <- pop_region_3338 %>%
    group_by(mgmt_area) %>%
    summarize(total_pop = sum(total_pop), do_union = F)

plot(pop_mgmt_3338["total_pop"])
```

```{r}
write_sf(pop_region_3338, "data/ak_regions_population.shp")
```



